version: "3.3"

services:
  mysql_service:
    container_name: mysql_service
    image: library/mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_volume:/var/lib/mysql
  web_service:
    container_name: web_service
    depends_on:
      - mysql_service
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm run build && npm run migration && npm run start"
    restart: always
    ports:
      - '3000:3000'
    links:
      - mysql_service:mysql_service
    environment:
      PORT: ${PORT}
      MYSQL_ADDR: ${MYSQL_ADDR}
      API_URL: ${API_URL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_DIALECT: ${DATABASE_DIALECT}
volumes:
  mysql_volume: